services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APMINSIGHT_LICENSE_KEY=${APMINSIGHT_LICENSE_KEY}
      - APMINSIGHT_APP_NAME=${APMINSIGHT_APP_NAME:-appcidemo-local}
      - APMINSIGHT_APP_PORT=${APMINSIGHT_APP_PORT:-8080}
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV:-dev}

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run cron
    restart: unless-stopped
    environment:
      - APMINSIGHT_LICENSE_KEY=${APMINSIGHT_LICENSE_KEY}
      - APMINSIGHT_APP_NAME=${APMINSIGHT_APP_NAME:-appcidemo-cron}
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV:-dev}
