services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: pm2-runtime start ecosystem.config.js --only app --watch
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - APMINSIGHT_LICENSE_KEY=${APMINSIGHT_LICENSE_KEY}
      - APMINSIGHT_APP_NAME=${APMINSIGHT_APP_NAME:-appcidemo-local}
      - APMINSIGHT_APP_PORT=${APMINSIGHT_APP_PORT:-8080}
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV:-dev}

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    command: pm2-runtime start ecosystem.config.js --only cron --watch
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - APMINSIGHT_LICENSE_KEY=${APMINSIGHT_LICENSE_KEY}
      - APMINSIGHT_APP_NAME=${APMINSIGHT_APP_NAME:-appcidemo-cron}
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV:-dev}
